### ISSUE TITLE
Plugin traceback when writing to thermostat API under python 2.6

### ISSUE THREAD

**Issue by allengray** [jdhorne/indigo-ecobee-plugin#11]
Getting this immediate traceback when loading the plugin under python2.6: 

Traceback (most recent call last):
File "plugin.py", line 286, in actionControlThermostat
File "plugin.py", line 340, in _handleChangeSetpointAction
ValueError: zero length field name in format

**Comment by allengray** [comment]
I've committed a fix, @jdhorne - Let me know whether I should instead make this in a branch and submit a pull request.

**Comment by allengray** [comment]
I'm going to edit the name of this from 'loading' -> 'writing to thermostat API'. 

This error only occurs when using python 2.6 or earlier (and possibly early python 3.x).
